### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by AdamMagaluk** [30x/enrober#135]
Getting the following error when I `GET /environments` but with `GET /environments/` i get the proper 401.

```
2017/02/17 20:48:18 http: panic serving 10.132.0.4:57120: runtime error: index out of range
goroutine 453 [running]:
net/http.(*conn).serve.func1(0xc4202ee900)
	/Users/bowenjosh/homebrew/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:1491 +0x12a
panic(0x12df400, 0xc42000a090)
	/Users/bowenjosh/homebrew/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:458 +0x243
github.com/30x/enrober/pkg/helper.AdminMiddleware.func1(0x7f70c7933118, 0xc4204361e0, 0xc4200acf00)
	/Users/bowenjosh/OSS/golang/src/github.com/30x/enrober/pkg/helper/adminValidation.go:39 +0x1bc
net/http.HandlerFunc.ServeHTTP(0xc420427e00, 0x7f70c7933118, 0xc4204361e0, 0xc4200acf00)
	/Users/bowenjosh/homebrew/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:1726 +0x44
github.com/30x/enrober/vendor/github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x1c162e0, 0xc420020010, 0x1c17a60, 0xc420427e00, 0x1c221e0, 0xc420306a90, 0xc4200acf00)
	/Users/bowenjosh/OSS/golang/src/github.com/30x/enrober/vendor/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/30x/enrober/vendor/github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc420427e20, 0x1c221e0, 0xc420306a90, 0xc4200acf00)
	<autogenerated>:15 +0x8b
net/http.serverHandler.ServeHTTP(0xc4202ef800, 0x1c221e0, 0xc420306a90, 0xc4200acf00)
	/Users/bowenjosh/homebrew/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4202ee900, 0x1c23120, 0xc4200c2a00)
	/Users/bowenjosh/homebrew/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/Users/bowenjosh/homebrew/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:2293 +0x44
```

**Comment by jbowen93** [comment]
This is likely caused by my sloppiness implementing the workaround for avoiding admin validation on status checks. Thanks for the bug report.
